sudo: required
services:
  - docker

before_install:
  - docker build -t kristapsvitols/docker-react -f Dockerfile.dev .

script:
  - docker run kristapsvitols/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-210844656426"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  access_secret_key:
    secure: "$AWS_SECRET_KEY"